### ISSUE TITLE
Expand / collapse animation speed 

### ISSUE THREAD

**Issue by WasimMemon** [futuresimple/android-floating-action-button#167] opened 2015-03-26 09:54 UTC
<pre>ANIMATION_DURATION = 300</pre> 
Can i change it from my class.?
I have seen FloatingActionsMenu class and there is no method to change this value.

**Comment by chalup** [comment] 2015-04-15 07:14
Duplicate of #97.

**Closed by chalup** 2015-04-15 07:14 UTC
