### ISSUE TITLE
Change Normal & Pressed Color Programatically

### ISSUE THREAD

**Issue by aritraroy** [futuresimple/android-floating-action-button#178] opened 2015-04-15 06:26 UTC
Is there a way to change the color of the Floating Menu programmatically using setNormalColor or setPressedColor methods. It is very important for me as I want to change the colors at run-time.

**Comment by chalup** [comment] 2015-04-15 07:08
Duplicate of #49

**Closed by chalup** 2015-04-15 07:08 UTC

**Comment by dkdilipkumar** [comment] 2017-07-04 11:40
I'm also need to change the "fab_addButtonColorPressed" color programatically.

**Comment by dkdilipkumar** [comment] 2017-07-04 11:41
I also need to change the "fab_addButtonColorPressed" pragmatically.
