### ISSUE TITLE
When setting custom drawable from code, icon is off center.

### ISSUE THREAD

**Issue by scmyers11** [futuresimple/android-floating-action-button#89] opened 2015-01-03 21:08 UTC
![erqwm4wzgyvvdyfpfzdhbvdy4i_xuojyjimyodkqqfu w308-h1286-no](https://cloud.githubusercontent.com/assets/1320013/5603723/226f9b8c-9359-11e4-8831-197ba9d4b2f1.png)

I am opening this issue because I noticed this when trying to use this library in my app.  Attached is the image of what is happening.  I am using fonticon to generate the drawables.  And because of that I have to set the drawable in code.  The only time the image is sized right is if the size of the drawable is exactly 72dp.  Any help would be appreciated.

**Comment by chalup** [comment] 2015-01-03 22:11
Please post your code and the drawable you use.

**Comment by scmyers11** [comment] 2015-01-03 22:25
Java to instantiate the drawable.

    FloatingActionButton printButton = (FloatingActionButton)rootView.findViewById(R.id.bol_print_action);
    Drawable print = FontIconDrawable.inflate(getActivity(), R.xml.ic_print);
    printButton.setIconDrawable(print);

Drawable:

    <font-icon
    xmlns:android="http://schemas.android.com/apk/res-auto"
    android:text="@string/fa_print"
    android:textSize="@dimen/fab_icon_size"
    android:textColor="@color/half_black"
    />

**Comment by scmyers11** [comment] 2015-01-04 15:54
Specifically I am using that FloatingActionButton inside of an FloatingActionMenu.

**Comment by alorma** [comment] 2015-01-05 13:22
I solved that using this in metod setIcoNDrawable:

https://gist.github.com/alorma/b117302a23c61761b2fa

**Comment by scmyers11** [comment] 2015-01-06 19:57
@alorma Since this is not a change I can make as a consumer of the api do you have a recommendation for how I can use this fix that you proposed?

**Comment by alorma** [comment] 2015-01-06 20:06
What i did is copy classes and use them standalone...

**Comment by scmyers11** [comment] 2015-01-06 20:26
@alorma thanks I'll give that a shot

**Comment by chalup** [comment] 2015-01-06 21:11
Actually the root cause of this problem is inside FontIconDrawable which doesn't respect `setBounds` call from LayerListDrawable used internally by FloatingActionButton. Workaround until it's fixed in fonticon lib is using the @alorma code inside the helper method:

```java
private Drawable fixIconFontDrawable(Drawable iconDrawable) {
    Bitmap bitmap = Bitmap.createBitmap(iconDrawable.getIntrinsicWidth(), iconDrawable.getIntrinsicHeight(), Bitmap.Config.ARGB_8888);
    Canvas canvas = new Canvas(bitmap);
    iconDrawable.setBounds(0, 0, canvas.getWidth(), canvas.getHeight());
    iconDrawable.draw(canvas);
    return new BitmapDrawable(getResources(), bitmap);
  }
```

**Closed by chalup** 2015-01-06 21:11 UTC
