### ISSUE TITLE
change the FloatingActionsMenu icon

### ISSUE THREAD

**Issue by idanbar134** [futuresimple/android-floating-action-button#176] opened 2015-04-12 13:47 UTC
Hello,

can i change the FloatingActionsMenu icon to custom icon?

Thanks,
Idan Ayalon

**Comment by Andrew-Quebe** [comment] 2015-04-13 21:47
Check this issue out: https://github.com/futuresimple/android-floating-action-button/issues/56

**Comment by chalup** [comment] 2015-04-15 07:01
Duplicate of #56.

**Closed by chalup** 2015-04-15 07:01 UTC

**Comment by jemshit** [comment] 2015-05-19 10:28
@chalup add option to change fab menu icon, ecen it is not great for now, just plus icon is not enough
