### ISSUE TITLE
Nested FAB's in FAM won't show titles

### ISSUE THREAD

**Issue by logineimer** [futuresimple/android-floating-action-button#133] opened 2015-02-03 19:47 UTC
Hello,

i try to put labels/titles beside my FAB's which are placed in a FAM just like in Google Inbox.
Do I have a mistake in my xml or is this a bug? My labels won't show up.

Thank you for this awesome library!

    <com.getbase.floatingactionbutton.FloatingActionsMenu
        android:id="@+id/party_menu"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_alignParentRight="true"
        android:layout_alignParentEnd="true"
        android:layout_marginRight="24dp"
        android:layout_marginEnd="24dp"
        android:layout_marginBottom="24dp"
        app:fab_addButtonPlusIconColor="@android:color/white"
        app:fab_addButtonColorNormal="@color/accent"
        app:fab_addButtonColorPressed="@color/accent_light"
        app:fab_addButtonSize="normal">

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/party_stopper"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:fab_icon="@drawable/ic_action_done"
            app:fab_title="Stop the party"
            app:fab_size="mini"/>

        <com.getbase.floatingactionbutton.FloatingActionButton
            android:id="@+id/party_round_adder"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:fab_icon="@drawable/ic_action_add"
            app:fab_title="Next go round!"
            app:fab_size="mini"/>

    </com.getbase.floatingactionbutton.FloatingActionsMenu>

**Comment by chalup** [comment] 2015-02-03 20:14
You need to set `fab_labelStyle` on your FAM. Let me know if this helps.

**Comment by sanathp** [comment] 2015-02-12 01:11
I have same issue on my android 4.3
Even after adding fab_labelStyle . I am not getting titles

**Comment by chalup** [comment] 2015-02-12 07:39
@logineimer did setting `fab_labelStyle` solve your issue?

@sanathp there is no way to set `fab_labelStyle` programatically yet, it's a part of #49 issue. Can you post your layout XML? Maybe there's something else missing (although I have no idea what that might be).

**Comment by logineimer** [comment] 2015-02-12 20:43
Good evening folks,
please apologise my late answer. :-)

Unfortunately, I didn't need the FAM anymore so I stopped investigating in this issue...
However, when I'm using the FAM in the future I will report if this issue still exists.

Greetings!

**Comment by ChrisDolge** [comment] 2015-02-17 20:12
Hi, 
I have this problem , that i can't see any label besides my FAB. I set fab_labelStyle. Here is my XML Code. 

```
  <com.getbase.floatingactionbutton.FloatingActionsMenu
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_alignParentBottom="true"
        android:layout_marginLeft="16dp"
        android:layout_marginStart="16dp"
        android:layout_alignRight="@+id/content"
        fab:fab_addButtonColorNormal="@color/accent"
        fab:fab_addButtonColorPressed="@color/accent"
        fab:fab_addButtonPlusIconColor="@color/primary"
        fab:fab_addButtonSize="mini"
        fab:fab_labelStyle="@style/menu_labels_style"
        fab:fab_labelsPosition="left">
```

I  also get an Error Message so i can not compile my project.

No resource identifier found for attribute 'fab_labelsPosition' in package '...'

**Comment by chalup** [comment] 2015-02-18 07:28
`fab_labelsPosition` are available since 1.8.0, which is being pushed to Maven Central as I type this :), so this error should be fixed as soon as the new version is available on Maven and you update your dependencies.

Regarding labels issue: where do you set the labels for individual buttons? What is the menu_labels_style? Does your application/activity have some custom style?

It would be great if you could post a full example reproducing this bug, because I've been scratching my head for a while about this issue.

**Comment by dgngulcan** [comment] 2015-02-18 11:54
I had same problem caused by wrong xmlns :
xmlns:fab were
    xmlns:fab="http://schemas.android.com/tools"   (auto import)
This import fix is fixed the issue, labels are now visible:
    xmlns:fab="http://schemas.android.com/apk/res-auto"

**Comment by themoonraker13** [comment] 2015-02-19 09:02
I am quite confused on how to use this library in my application. There are a lot of floating action button components inside xml layout file of the sample. Can someone help me out on how to begin from 'A'.

**Comment by chalup** [comment] 2015-03-08 21:35
It seems the issue is resolved. Please let me know if you still have problems with labels with a) correctly set `xmlns` and b) `fab_labelsPosition` set?

**Closed by chalup** 2015-03-08 21:35 UTC

**Comment by Ph1b** [comment] 2015-04-17 21:33
I think the default behavior should be to use some standard style. You can get the color primary from the system and decide by that if its a dark or light theme.
When someone sets a label, he expects the label to show, otherwise he would not have set it.

**Comment by achavhan** [comment] 2016-02-20 13:53
@dgngulcan ur a lifesaver. @chalup thanks for wonderrfull library

**Comment by sreekuttan9991** [comment] 2017-06-28 07:04
Is there any way to set fab_labelsPosition of FAM programmatically? Because for developing apps which support RTL and LTR its necessary.
