### ISSUE TITLE
FloatingActionButtonMenu with different icon

### ISSUE THREAD

**Issue by jamoque** [futuresimple/android-floating-action-button#216] opened 2015-06-10 01:37 UTC
Is it possible to create a FloatingActionButtonMenu item with an icon that isn't a plus. Specifically I was hoping to use a vertical ellipsis like the one that would normally be seen in the ActionBar. I have tried looking through the source, but with no luck. Any help is appreciated!

**Comment by koustuvsinha** [comment] 2015-06-18 18:03
:+1: Need this api, both from xml and programmatically

**Comment by brandoFS** [comment] 2015-06-24 21:21
I would also like this

**Comment by chalup** [comment] 2015-06-30 07:27
Duplicate of #56

**Closed by chalup** 2015-06-30 07:27 UTC

**Comment by Aasif312** [comment] 2016-06-11 12:47
This should work

       floatingActionMenu.setIconAnimated(false);

       floatingActionMenu.setOnMenuToggleListener(new FloatingActionMenu.OnMenuToggleListener() {
            @Override
            public void onMenuToggle(boolean opened) {
                if (opened)
                {
                		floatingActionMenu.getMenuIconView().invalidateDrawable
                		(
          		        floatingActionMenu.getMenuIconView().getDrawable()  
          		        );
        			    floatingActionMenu.getMenuIconView().setImageBitmap(
                			BitmapFactory.decodeResource(
                        			getResources(), R.drawable.<YOUR_DRAWABLE_ID>
                					)
        				);
                }
                    
                else
                {
                	floatingActionMenu.getMenuIconView().invalidateDrawable
                		(
          		        floatingActionMenu.getMenuIconView().getDrawable()  
          		        );
        			    floatingActionMenu.getMenuIconView().setImageBitmap(
                			BitmapFactory.decodeResource(
                        			getResources(), R.drawable.<YOUR_DRAWABLE_ID>
                					)
        				);

                }
                     
            }
        });
